spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://pedidos360-db-nano.postgres.database.azure.com:5432/postgres?sslmode=require}
    username: ${DB_USERNAME:adminpedidos}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/bb5324af-c266-41ed-b36c-a971641c7af2/v2.0

logging:
  level:
    org.springframework.security: INFO